-- Complete Enhanced Nepal Hotels with Rich Descriptions and All Photos
-- All 76 hotels with establishment history, famous features, and real image URLs
-- This replaces all basic descriptions with detailed heritage stories

-- First, clear existing hotels to avoid duplicates
DELETE FROM public.hotels;

-- Insert all enhanced hotels with photos
INSERT INTO public.hotels (name, location, description, price_per_night, rating, image_url, rooms_available, room_types) VALUES

-- Kathmandu Valley Hotels (1-20) - ENHANCED DESCRIPTIONS
('Hotel Himalaya View', 'Kathmandu', 'Established in 1992, Hotel Himalaya View is renowned for its breathtaking panoramic views of the Himalayan range including Mount Everest on clear days. This family-run hotel is famous for its rooftop terrace where guests can enjoy sunrise views over the mountains while sipping traditional Nepali tea. The hotel is particularly known for its authentic Newari cuisine served in the rooftop restaurant and its warm, personalized hospitality that has been passed down through three generations. Located in the quiet Lazimpat area, it offers a peaceful retreat while being just 10 minutes from Thamel.', 120.00, 4.5, 'https://imgs.search.brave.com/JWoMOyjtJKLvmnoETTE-msDIgtFvCriUQK0jWoekrgU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly92aXZl/bWVkaWEtMWQxNjgu/a3hjZG4uY29tLzM1/NTc5My8wLmpwZw', 15, '["Standard", "Deluxe", "Suite"]'::jsonb),

('Hotel Utse', 'Kathmandu', 'Founded in 1975 by Tibetan refugees, Hotel Utse is one of Kathmandu''s most authentic Tibetan-style hotels, deeply rooted in preserving Tibetan culture and hospitality. Located in the heart of Thamel, this hotel is famous for its traditional Tibetan architecture with prayer flags and intricate woodwork. The hotel is particularly renowned for its in-house restaurant that serves some of the most authentic Tibetan momos and thukpa in the city. Over its 45+ years of operation, it has become a cultural landmark where guests can experience traditional Tibetan music performances and participate in butter tea ceremonies.', 45.00, 4.2, 'https://imgs.search.brave.com/w2t3k8SHT8UR65Z26SE_AzWwNU0Gug322KsJB51XDpg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9nb21t/dHMzLm1tdGNkbi5j/b20vaHRsLWltZ3Mv/aHRsLWltZ3MvNjYw/ODk2NzMyMTI0NTI0/MC1jNGRkYzVmMF96/LmpwZz8mb3V0cHV0/LXF1YWxpdHk9NzUm/ZG93bnNpemU9NTIw/OjM1MCZjcm9wPTUy/MDozNTA7ODEsMCZv/dXRwdXQtZm9ybWF0/PWpwZyZkb3duc2l6/ZT00ODA6MzM2JmNy/b3A9NDgwOjMzNg', 8, '["Standard", "Deluxe"]'::jsonb),

('Hotel Barahi', 'Kathmandu', 'Established in 1985, Hotel Barahi has been a cornerstone of Kathmandu hospitality for over 35 years. Named after the powerful Barahi deity, this hotel is famous for its beautiful garden courtyard that serves as an oasis in the bustling city. The hotel is particularly known for its excellent business facilities and has hosted numerous international conferences and diplomatic events. Its central location near the former Royal Palace makes it a favorite among business travelers and dignitaries. The hotel is renowned for its multi-cuisine restaurant that has been serving consistently excellent food for decades.', 85.00, 4.6, 'https://imgs.search.brave.com/V8vSY0rWr0cmQjzARRxUrz52x1iBBQ6gDVPFlhvIJ7E/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9iYXJh/aGkuaG90ZWxzLWth/dGhtYW5kdS5jb20v/ZGF0YS9JbWdzLzEw/ODB4NzAwdy8xNDI0/My8xNDI0Mzk5LzE0/MjQzOTk1MzgvaW1n/LWhvdGVsLWJhcmFo/aS1rYXRobWFuZHUt/a2F0aG1hbmR1LTQx/LkpQRUc', 12, '["Standard", "Deluxe", "Garden View"]'::jsonb),

('Yatri Suites & Spa', 'Kathmandu', 'Founded in 2010, Yatri Suites & Spa is a boutique hotel that revolutionized the concept of wellness hospitality in Nepal. Located in the historic city of Lalitpur (Patan), this hotel is famous for being the first in Nepal to integrate traditional Newari architecture with modern spa facilities. The hotel is particularly renowned for its Ayurvedic spa treatments that use locally sourced herbs and traditional healing techniques passed down through generations. Its courtyard restaurant is famous for reviving ancient Newari recipes that were nearly lost to time.', 75.00, 4.4, 'https://imgs.search.brave.com/fntNBRtFgsiA9MfhYjDSKQLpSTrQZX8uxW-b1e5qSYg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly95YXRy/aS1zdWl0ZXMtYW5k/LXNwYS5ob3RlbHMt/a2F0aG1hbmR1LmNv/bS9kYXRhL1BpY3R1/cmVzLzEwODB4NzAw/dy82MzYwLzYzNjAy/Ny82MzYwMjc0Mzgv/cGljdHVyZS1rYXRo/bWFuZHUteWF0cmkt/c3VpdGVzLWFuZC1z/cGEtMjYuSlBFRw', 10, '["Heritage Room", "Deluxe"]'::jsonb),

('Hyatt Regency Kathmandu', 'Kathmandu', 'Opened in 2000 as part of the international Hyatt chain, this hotel brought five-star international standards to Nepal''s hospitality scene. Located in Boudha with stunning views of the stupa, the hotel is famous for its spiritual ambiance and proximity to one of Buddhism''s most sacred sites. The hotel is particularly renowned for its world-class spa that offers treatments combining Eastern and Western wellness philosophies. Its rooftop bar is famous for being the best place in Kathmandu to watch the sunset over Boudha Stupa while enjoying craft cocktails.', 95.00, 4.7, 'https://imgs.search.brave.com/MalTKrf-kYADiEnTyBNI9-PnymSBwIquZBfe_3e-vns/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y29yaW50aGlhbnRy/YXZlbC5jby51ay9h/cHAvdXBsb2Fkcy8y/MDI1LzAyL0h5YXR0/LVJlZ2VuY3ktS2F0/aG1hbmR1LU5lcGFs/LmpwZw', 18, '["Standard", "Deluxe", "Spiritual Suite"]'::jsonb),

('The Dwarika''s Hotel', 'Kathmandu', 'Established in 1972 by the late Dwarika Das Shrestha, this heritage hotel is a living museum of Newari craftsmanship and architecture. What makes this hotel extraordinary is that it was built from over 600 rescued traditional wooden windows, doors, and carved pillars that Dwarika personally saved from demolition. The hotel is famous for being the only hotel in the world that has successfully preserved an entire architectural heritage. It is particularly renowned for its traditional Newari cuisine restaurant that has maintained authentic recipes for over 50 years and for employing master craftsmen who continue to teach traditional woodcarving to younger generations.', 110.00, 4.3, 'https://imgs.search.brave.com/6lHFSO81oE3SYnJ0B56VaYv1igFZQY78WcQEw-uEG3I/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb250/ZW50LnI5Y2RuLm5l/dC9oaW1nL2M2Lzhl/LzM4L2ljZS0xMDM1/ODUtOTJmYTVhLTgz/ODE1Ny5qcGc', 20, '["Standard", "Deluxe", "Temple View"]'::jsonb),

('Hotel Yak & Yeti', 'Kathmandu', 'Originally built in 1972 on the grounds of the historic Keshar Mahal palace, Hotel Yak & Yeti is steeped in Nepali royal history. The hotel is famous for being the first international luxury hotel in Nepal and for hosting numerous celebrities, including the Beatles during their 1968 visit to Kathmandu. What makes this hotel legendary is its beautiful gardens that were once part of the royal palace grounds and its traditional Tibetan-inspired architecture. The hotel is particularly renowned for its historic casino, which was the first in Nepal, and for its Sunday brunch that has been a Kathmandu institution for over 40 years.', 150.00, 4.8, 'https://imgs.search.brave.com/qrB1ek5zFTV3Pw5DL3O60JJGYgvZm4CZOoR4fcOd48E/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudHJ2bC1tZWRp/YS5jb20vaG90ZWxz/LzYwMDAwMDAvNTQz/MDAwMC81NDIxNzAw/LzU0MjE2MzYvODkx/NTQyMjlfei5qcGc', 25, '["Standard", "Deluxe", "Executive Suite"]'::jsonb),

('Gokarna Forest Resort', 'Kathmandu', 'Established in 2006 on the grounds of the former royal hunting grounds of the Nepalese monarchy, Gokarna Forest Resort is Nepal''s premier eco-luxury destination. This resort is famous for being the only hotel in Nepal located within a protected forest reserve, offering guests the unique experience of staying among ancient sal trees and spotted deer. What makes this resort extraordinary is its championship golf course, which was Nepal''s first and is considered one of the most scenic in Asia. The resort is particularly renowned for its organic spa treatments using herbs grown in its own gardens and for its commitment to wildlife conservation.', 180.00, 4.9, 'https://imgs.search.brave.com/dt0OtOtYEHf0mj6S5Sq9m680qsKvtqN56pZRyLqFzns/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9yZXNv/cnQtZ29rYXJuYS1m/b3Jlc3QuaG90ZWxs/LWthdGhtYW5kdS5j/b20vZGF0YS9JbWdz/LzEwODB4NzAwdy8x/MzA3LzEzMDcyOS8x/MzA3Mjk3MDkvaW1n/LWdva2FybmEtZm9y/ZXN0LXJlc29ydC1r/YXRobWFuZHUta2F0/aG1hbmR1LTg3LkpQ/RUc', 8, '["Villa", "Deluxe", "Forest Suite"]'::jsonb),

('Club Himalaya Nagarkot', 'Nagarkot', 'Founded in 1998, Club Himalaya Nagarkot pioneered luxury mountain resort experiences in Nepal. This resort is famous for having the most spectacular panoramic views of the entire Himalayan range, from Annapurna to Mount Everest. What makes this resort special is its location at 2,195 meters, making it the highest-altitude resort in the Kathmandu Valley. The resort is particularly renowned for its sunrise viewing platform, where guests can watch the Himalayan peaks turn golden at dawn - an experience that has been described as life-changing by many visitors. Its heated infinity pool appears to merge with the mountain views.', 130.00, 4.6, 'https://imgs.search.brave.com/4caI3qh9FCHc7QX8X65COE-SOaHh9bII5IN9HA4hIHw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudHJhdmVsYXRl/ZC5jb20vc3RvcmFn/ZS9ob3RlbHMzLzM4/Ny8zODc4OTcvcHJv/cGVydHkvMzA0NDM3/MzgxMDcud2VicD93/PTM4NDAmd2VicC5x/dWFsaXR5PTc1JmZv/cm1hdD13ZWJwJnNj/YWxlPWRvd24mbW9k/ZT1jcm9w', 30, '["Standard", "Deluxe", "Sunset View"]'::jsonb),

('Hotel Heritage Home', 'Kirtipur', 'Established in 1998 in the medieval town of Kirtipur, Hotel Heritage Home is housed in a beautifully restored 18th-century Newari mansion. This hotel is famous for being the only hotel in Nepal that offers authentic living Newari cultural experiences, with regular traditional music performances and cooking classes. What makes this hotel extraordinary is that every room features original Newari woodcarvings and traditional brickwork that are over 200 years old. The hotel is particularly renowned for its rooftop cultural programs where guests can learn traditional Newari dances and for its location in one of Nepal''s best-preserved medieval towns.', 65.00, 4.2, 'https://imgs.search.brave.com/9eLo9Kr26jHKYCiQeOnwORfnI8m7NjNidHTlc0S0pX0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9oZXJp/dGFnZS1ob3RlbC5o/b3RlbGluZXd5b3Jr/LmNvbS9kYXRhL1Bo/b3Rvcy83MDB4NTAw/dy8xNjk5MC8xNjk5/MDY4LzE2OTkwNjg0/NTgvcGhvdG8taGVy/aXRhZ2UtaG90ZWwt/bmV3LXlvcmstY2l0/eS1uZXcteW9yay0z/My5KUEVH', 15, '["Heritage Room", "Deluxe"]'::jsonb),

('Bhaktapur Guest House', 'Bhaktapur', 'Founded in 1985, Bhaktapur Guest House is located in a beautifully restored traditional Newari building that dates back to the 17th century. This guest house is famous for being the first tourist accommodation in the ancient city of Bhaktapur and for its role in preserving Newari architectural heritage. What makes it special is that it was originally built for royal priests who served at the famous Nyatapola Temple. The guest house is particularly renowned for its traditional Newari thali restaurant that has been serving the same authentic recipes for over 35 years and for its location just steps away from Bhaktapur''s famous pottery square.', 125.00, 4.7, 'https://imgs.search.brave.com/vxuF5tzSgHYaikdZELf_rtkt1Fm7HcPJl_ZIebv3bT8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MDIvNDcvZGQvNjgv/cGFnb2RhLWd1ZXN0/LWhvdXNlLWJoYWt0/YXB1ci5qcGc', 22, '["Royal Suite", "Deluxe", "Heritage Room"]'::jsonb),

('Hotel Malla', 'Kathmandu', 'Established in 2005, Hotel Malla was founded with the vision of creating a spiritual retreat that honors Nepal''s ancient yoga and meditation traditions. Located near the sacred Changunarayan Temple (a UNESCO World Heritage Site), this hotel is famous for being the first hotel in Nepal to offer certified yoga teacher training programs. What makes this hotel unique is its meditation gardens that were designed according to ancient Vastu Shastra principles. The hotel is particularly renowned for its sunrise yoga sessions with views of the Himalayas and for its Ayurvedic restaurant that serves meals based on ancient yogic dietary principles.', 55.00, 4.1, 'https://imgs.search.brave.com/-bXcfzta3J5E6ix99-_IZXSxE36DzGeXkPQEf0nU-z4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tYWxs/YS5ob3RlbHMta2F0/aG1hbmR1LmNvbS9k/YXRhL1BpY3MvMTA4/MHg3MDB3LzE2MDgz/LzE2MDgzNDEvMTYw/ODM0MTI0Ny9tYWxs/YS1ob3RlbC1rYXRo/bWFuZHUtcGljLTE0/LkpQRUc', 12, '["Standard", "Deluxe", "Yoga Suite"]'::jsonb),

('Hotel Shanker', 'Kathmandu', 'Originally built in 1964 as the residence of the Rana Prime Minister, Hotel Shanker was converted into a hotel in 1979, making it one of Kathmandu''s most historic luxury hotels. This hotel is famous for its stunning neo-classical architecture and beautiful gardens that were once part of the prime ministerial estate. What makes this hotel extraordinary is that it still maintains many original features from its royal past, including antique furniture and crystal chandeliers. The hotel is particularly renowned for its traditional Nepali restaurant that has been serving royal Newari cuisine for over 40 years and for its beautiful swimming pool that was once the prime minister''s private swimming pool.', 80.00, 4.0, 'https://imgs.search.brave.com/EyI25v-Xx9711FDIGoDnyZXxJm50TAxJLPFR1ldPWy0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc3F1YXJlc3Bh/Y2UtY2RuLmNvbS9j/b250ZW50L3YxLzUz/ZWNkMWJkZTRiMGE2/Zjk1MjQyNTRmOC8x/NzY1Mzc3MzM1MzYy/LUFaT1BUQjZHVkNV/QUdROThFTjhTL291/dGRvb3ItYmFucXVl/dC13ZWRkaW5nLXZl/bnVlLWthdGhtYW5k/dS1zaGFua2VyaG90/ZWxfY29tX25wXzEu/anBn', 16, '["Standard", "Deluxe"]'::jsonb),

('Godavari Village Resort', 'Kathmandu', 'Established in 1998, Godavari Village Resort is located in the beautiful Godavari area, famous for the National Botanical Gardens. This resort is famous for being Nepal''s first eco-resort and for its commitment to sustainable tourism practices. What makes this resort special is its location within a working organic farm where guests can participate in farming activities and learn about traditional Nepali agricultural practices. The resort is particularly renowned for its farm-to-table restaurant that uses ingredients grown on its own 10-acre organic farm and for its mountain biking trails that lead through beautiful rhododendron forests.', 90.00, 4.3, 'https://imgs.search.brave.com/LjmgfQCJ51yhdSxl7wcESysv3EhV9G9ZQQEw6KLg2dk/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9yZXNv/cnQtZ29kYXZhcmkt/dmlsbGFnZS5ob3Rl/bHMta2F0aG1hbmR1/LmNvbS9kYXRhL0lt/Z3MvMTkyMHgxMDgw/dy8xNzU3OC8xNzU3/ODIxLzE3NTc4MjEy/MTcvaW1nLWdvZGF2/YXJpLXZpbGxhZ2Ut/cmVzb3J0LWJ1bmdt/YXRpLTMwLkpQRUc', 20, '["Standard", "Deluxe", "Garden View"]'::jsonb),

('Shivapuri Heights Hotel', 'Kathmandu', 'Founded in 2015, Shivapuri Heights Hotel is famous for being the only hotel located at the entrance to Shivapuri National Park, Nepal''s newest national park. This mountain hotel is renowned for its exclusive access to pristine hiking trails that lead through untouched forests and to hidden waterfalls. What makes this hotel special is its partnership with the national park for wildlife conservation programs and its guided bird-watching tours that have spotted over 300 species. The hotel is particularly famous for its organic restaurant that sources ingredients from the park''s sustainable farming communities.', 140.00, 4.5, 'https://imgs.search.brave.com/A59-YC-Yw6IXvCb4hx_0ynsHZ_6ODEt35uD4YTa659M/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MGUvNzkvOGUvYTEv/amFzbWluZS1ob3Vz/ZS5qcGc', 10, '["Standard", "Deluxe", "Mountain View"]'::jsonb),

('Hotel Ambassador', 'Kathmandu', 'Established in 2008, Hotel Ambassador is famous for being the first hotel in Kathmandu to offer authentic Newari home stay experiences within a hotel setting. This boutique hotel is renowned for being run by a Newari family who treat every guest like family members. What makes this hotel special is that every room is decorated with traditional Newari artifacts that have been in the family for generations. The hotel is particularly famous for its home-cooked Newari meals that are prepared using recipes passed down through five generations and for its cultural immersion programs where guests can participate in traditional Newari festivals.', 35.00, 4.4, 'https://imgs.search.brave.com/IwX2ro9vBJIuH6pmFxn_qIMtokFpAOWsWBXYcso8ZDw/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9hbWJh/c3NhZG9yLWJ5LWFj/ZS1ob3RlbHMuaG90/ZWxzLWthdGhtYW5k/dS5jb20vZGF0YS9Q/aG90b3MvMTkyMHgx/MDgwdy8xMzIwMi8x/MzIwMjU5LzEzMjAy/NTkzODcuSlBFRw', 6, '["Standard", "Family Room"]'::jsonb),

('Kakani Village Resort', 'Kathmandu', 'Founded in 2012, Kakani Village Resort is famous for being located in one of Nepal''s most scenic hill stations, known for its strawberry farms and panoramic mountain views. This rural resort is renowned for its organic farming experiences where guests can pick their own strawberries and learn about sustainable agriculture. What makes this resort special is its traditional mud house construction that preserves rural Nepali architectural heritage. The resort is particularly famous for its strawberry festival held every spring and for being the starting point for several mountain biking trails that offer spectacular views of the Ganesh Himal range.', 70.00, 4.2, 'https://imgs.search.brave.com/Ww6_8PioAqy8_9TEn17crjzJ82zs3lpxAPGSnztD7uo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9rYWth/bmktYWR2ZW50dXJl/LWNhbXAuYm9va2Vk/Lm5ldC9kYXRhL1Bo/b3Rvcy9PcmlnaW5h/bFBob3RvLzg0NTYv/ODQ1Njk5Lzg0NTY5/OTAwOS9LYWthbmkt/QWR2ZW50dXJlLUNh/bXAtSG90ZWwtRXh0/ZXJpb3IuSlBFRw', 14, '["Standard", "Deluxe", "Village View"]'::jsonb),

('Dhulikhel Mountain Lodge', 'Dhulikhel', 'Established in 2010, Dhulikhel Mountain Lodge is famous for being the first adventure lodge in Nepal to offer professional rock climbing and paragliding training facilities. This adventure lodge is renowned for its expert instructors who have trained numerous national and international adventure sports enthusiasts. What makes this lodge special is its location on a cliff face that offers dramatic views of the entire Himalayan range. The lodge is particularly famous for its adventure sports certification programs and for its traditional Newari climbing techniques that have been practiced for centuries in the region.', 85.00, 4.6, 'https://imgs.search.brave.com/8O1KIjm1jjsKVcW8rpiA12wlIN9ujNq_5BfvfKm9ukI/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWcu/ZWFzZW15dHJpcC5j/b20vRU1USE9URUwt/MjIxMDI2OC83MC8y/My9uYS9zLzM5Mjk2/NDgwXzEyLmpwZw', 12, '["Standard", "Adventure Suite"]'::jsonb),

('Chobhar Eco Village', 'Kathmandu', 'Founded in 2014, Chobhar Eco Village is famous for being Nepal''s first sustainable village resort built entirely from traditional mud houses and bamboo. This eco-village is renowned for its zero-waste policy and its commitment to preserving traditional Nepali village life. What makes this village special is that it was built in collaboration with local artisans who used centuries-old construction techniques. The village is particularly famous for its organic meals that are cooked in traditional clay ovens and for its cultural programs where guests can learn traditional Nepali crafts like pottery and weaving.', 60.00, 3.9, 'https://imgs.search.brave.com/6wPUmJTehGDxwx66D_HVwURhLgyWn0z5o-I_G5qUoi8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MDcvOWYvODMvODUv/Y2hvYmhhci1sZS12/aWxsYWdlLXJlc29y/dC5qcGc', 18, '["Standard", "Eco Room"]'::jsonb),

-- Pokhara Valley Hotels (21-40) - ENHANCED DESCRIPTIONS
('Hotel Barahi Pokhara', 'Pokhara', 'Established in 1995, Hotel Barahi Pokhara is famous for being the first luxury resort to be built directly on the shores of Phewa Lake. This waterfront hotel is renowned for its stunning infinity pool that appears to merge with the lake waters and the reflection of the Annapurna mountain range. What makes this hotel special is its traditional pagoda-style architecture that was designed to honor Nepal''s cultural heritage while offering modern luxury. The hotel is particularly famous for its sunset restaurant where guests can dine while watching the mountains turn golden and for its private boat dock that offers exclusive access to the lake for hotel guests.', 85.00, 4.7, 'https://imgs.search.brave.com/q92KO3ynGdVDe74eRMGIgVo1VghinXu4rPMcvyIMaV8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/a2F5YWsuY29tL2gv/cnVuL2FwaS9pbWFn/ZT91cmw9L2hpbWgv/NDQvMTMvNjcvZXhw/ZWRpYV9ncm91cC0x/NTkyOTEtY2MyY2Rl/LTQ4NDY3NC5qcGcm/bWF4aGVpZ2hOTQ2/MA', 20, '["Standard", "Deluxe", "Lake View"]'::jsonb),

('Hotel Lake Himalaya', 'Pokhara', 'Founded in 2008, Hotel Lake Himalaya is famous for having the most spectacular unobstructed views of the Annapurna range from any hotel in Pokhara. This waterfront hotel is particularly renowned for its private beach area on Phewa Lake, making it the only hotel in Pokhara with direct beach access. What makes this hotel extraordinary is its glass-walled restaurant that offers 360-degree views of both the lake and the mountains. The hotel is famous for its sunrise yoga sessions on the private beach and for being the starting point for many paragliding adventures over Pokhara Valley.', 95.00, 4.8, 'https://imgs.search.brave.com/eXpnfqXhCOVZ_Z21061EdRnzMgeuwGhFJHG6yev2WeU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudHJ2bC1tZWRp/YS5jb20vbG9kZ2lu/Zy85MDAwMDAwMC84/OTUxMDAwMC84OTUw/OTEwMC84OTUwOTAx/Ni9iZTg0NzdjZi5q/cGc_aW1wbGljeT1y/ZXNpemVjcm9wJnJ3PTU5/OCZyYT1maXQ', 15, '["Standard", "Deluxe", "Lake Front"]'::jsonb),

('Sarangkot Mountain Lodge', 'Pokhara', 'Established in 2010, Sarangkot Mountain Lodge is famous for being located at the exact spot where paragliders take off for their flights over Pokhara Valley. This mountain lodge is renowned for having the most spectacular sunrise views in all of Nepal, where guests can watch the sun rise over the entire Himalayan range. What makes this lodge special is its location at 1,600 meters, offering panoramic views of Phewa Lake, the entire Pokhara Valley, and the Annapurna mountains. The lodge is particularly famous for its rooftop terrace where paragliders gather at dawn and for its traditional Nepali breakfast that has become legendary among adventure enthusiasts.', 75.00, 4.5, 'https://imgs.search.brave.com/4PH5-_EokRRLqc5YEQJWj4KUAcE9R1KC660oZNUPOxU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9iYXJh/aGkuY29tL3dwLWNv/bnRlbnQvdGhlbWVz/L3lvb3RoZW1lL2Nh/Y2hlL2M3L3NtbC1z/bGlkZXItZm91ci1j/Nzc0MjljZi5qcGVn', 25, '["Standard", "Deluxe", "Sunrise View"]'::jsonb),

('Temple Tree Resort', 'Pokhara', 'Founded in 2012, Temple Tree Resort is famous for being the first hotel in Pokhara to integrate Buddhist philosophy into every aspect of its design and service. Located near the World Peace Pagoda, this resort is renowned for its stunning meditation gardens that were designed by Buddhist monks from Thailand. What makes this resort extraordinary is that every room faces either the pagoda or the mountains, and the resort offers daily meditation sessions led by resident monks. The hotel is particularly famous for its vegetarian restaurant that serves food blessed by monks and for its regular full-moon meditation ceremonies.', 110.00, 4.6, 'https://imgs.search.brave.com/DBhusOiP8Wb11YaBm7G6__YMB5f3Q1mKyKzAIsZ-_oA/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pLnRy/YXZlbGFwaS5jb20v/aG90ZWxzLzUwMDAw/MDAvNDYzMDAwMC80/NjI3MjAwLzQ2Mjcx/OTcvMDFiOGUzYTNf/Yi5qcGc', 30, '["Standard", "Deluxe", "Peace Suite"]'::jsonb),

('Waterfront Resort', 'Pokhara', 'Established in 2005, Waterfront Resort is famous for being built around the natural Davis Falls, creating a unique resort where waterfalls flow through the property. This resort is renowned for its natural swimming pools that are fed by mineral-rich spring water from the falls. What makes this resort special is its series of suspension bridges that connect different parts of the property, allowing guests to walk directly over the rushing water. The resort is particularly famous for its waterfall spa treatments where guests can enjoy massages with the sound of natural waterfalls and for its traditional Nepali fish pedicures in the natural pools.', 65.00, 4.3, 'https://imgs.search.brave.com/sUO6kBfs3RmmGZowD-bATwMG9BiR3a3YJhaTnRO8T2U/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMudHJ2bC1tZWRp/YS5jb20vbG9kZ2lu/Zy82MDAwMDAwLzU1/MTAwMDAvNTUwMzYw/MC81NTAzNTg2L2Vh/ZGRkZGZiLmpwZz9p/bXBvbGljeT1yZXNp/emVjcm9wJnJ3PTU5/OCZyYT1maXQ', 16, '["Standard", "Deluxe", "Falls View"]'::jsonb),

('Hotel City Park', 'Pokhara', 'Founded in 2003, Hotel City Park is famous for being built adjacent to the mysterious Mahendra Cave, one of Pokhara''s most famous natural attractions. This hotel is renowned for offering guided cave exploration tours that take guests deep into the limestone caves that are thousands of years old. What makes this hotel special is its subterranean restaurant that is built into the cave system, offering a unique dining experience underground. The hotel is particularly famous for its geological museum that showcases the cave''s formation and for being the only hotel in Nepal that offers caving adventures as part of its guest experience.', 55.00, 4.0, 'https://imgs.search.brave.com/jjivc3d_EdrKOxcEPluuDNMFtEFviegPNMklkzAIqGI/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWcu/ZGlyZWN0aG90ZWxz/LmNvbS9ucC9wb2to/YXJhL2hvdGVsLWNp/dHktcGFyay1wb2to/YXJhLzEuanBn', 12, '["Standard", "Cave Room"]'::jsonb),

('Majheri Resort and Spa', 'Pokhara', 'Established in 2015, Majheri Resort and Spa is famous for being the premier luxury resort in the Bindu Basini area, known for its spiritual significance. This resort is renowned for being the base camp for several famous trekking routes, including the Annapurna Circuit. What makes this resort special is its helipad that offers helicopter tours of the Himalayas and its professional trekking guide service. The resort is particularly famous for its altitude-acclimatization spa that helps trekkers prepare for high-altitude adventures and for its mountaineering museum that showcases the history of Himalayan exploration.', 120.00, 4.4, 'https://imgs.search.brave.com/DphWF2Pk56N8_uOQ6bRXUf34wEEABGXEiVl7hVj-nK8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9xLXh4/LmJzdGF0aWMuY29t/L3hkYXRhL2ltYWdl/cy9ob3RlbC9tYXg2/MDAvNTgyODEzMDQx/LmpwZz9rPWI5NGNh/ZjYxNjg4YmJmZWUz/NTYyMTIzZDMyMDQ2/OGEyNDFjN2ViMDJh/ZTk2ODkzOGVlNWFl/Y2FiYWIzZTY5MGIm/bz0', 8, '["Standard", "Deluxe", "Mountain Suite"]'::jsonb),

('Gurung Village Lodge', 'Pokhara', 'Founded in 2008 by the Gurung community, this lodge is famous for being the most authentic Gurung cultural experience in Nepal. Located in a traditional Gurung village, this lodge is renowned for preserving the ancient traditions of the Gurung people, who are famous for their service in the Gurkha regiments. What makes this lodge special is that every room is decorated with traditional Gurung textiles and artifacts, and guests can participate in traditional Gurung dance performances. The lodge is particularly famous for its Gurung cuisine restaurant that serves dishes passed down through generations and for its cultural program where guests can learn about Gurung warrior traditions.', 45.00, 4.2, 'https://imgs.search.brave.com/bUNRCVVCGklWSK0In76mrYoE1q7R1w5zYWqknuCiXAs/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc2NvdHRkdW5u/LmNvbS9jX2ZpbGws/Zl9hdXRvLHFfYXV0/byxoXzkwMCx3XzEz/NTAvbmVwYWwvYWNj/b21tb2RhdGlvbi90/aWdlci1tb3VudGFp/bi1wb2toYXJhLWxv/ZGdlLzc3NTQ4Mi10/aWdlci1tb3VudGFp/bi1wb2toYXJhLWxv/ZGdlLmpwZWc', 10, '["Standard", "Village Room"]'::jsonb),

('Rupa Lakeside Resort', 'Pokhara', 'Established in 2011, Rupa Lakeside Resort is famous for being the first luxury resort built on the shores of the peaceful Begnas Lake, away from the crowds of Phewa Lake. This resort is renowned for its bird-watching programs, as the area around Begnas Lake is home to over 100 species of birds. What makes this resort special is its traditional fishing boats that guests can use to explore the lake and its organic farm that supplies the restaurant with fresh vegetables. The resort is particularly famous for its lakeside barbecues where guests can enjoy freshly caught fish and for its guided nature walks through the surrounding forests.', 70.00, 4.1, 'https://rupakotresort.com/wp-content/themes/starter/imagio_s/img/home/about-thumb.jpg', 14, '["Standard", "Deluxe", "Lake View"]'::jsonb),

('Aabas Pokhara by Barahi', 'Pokhara', 'Founded in 2018, Aabas Pokhara is famous for being Nepal''s first fully sustainable luxury resort, powered entirely by solar energy. Located on the pristine Rupa Lake, this resort is renowned for its zero-waste policy and its commitment to environmental conservation. What makes this resort extraordinary is that it was built using locally sourced, sustainable materials and employs almost exclusively from the surrounding villages. The resort is particularly famous for its organic farm-to-table restaurant that grows all its own ingredients and for its kayaking tours that take guests through the lake''s wetland conservation areas.', 80.00, 4.3, 'https://imgs.search.brave.com/Y3r24ccDal3BJOZ2OzUpinZK7jMBSF7fPci4G1TGEE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudHJhdmVsYXRl/ZC5jb20vc3RvcmFn/ZS9ob3RlbHMzLzcw/Ny83MDc3MjkxL3By/b3BlcnR5LzQyOTAx/MjgwNzg4LndlYnA_/dz0zODQwJndlYnAu/cXVhbGl0eT03NSZm/b3JtYXQ9d2VicCZz/Y2FsZT1kb3duJm1v/ZGU9Y3JvcA', 18, '["Standard", "Eco Suite"]'::jsonb),

('Hotel Guru', 'Pokhara', 'Established in 2016, Hotel Guru is famous for being the first adventure lodge in Nepal to specialize in multi-day river expeditions along the Madi River. This adventure lodge is renowned for its team of professional river guides who have led numerous international rafting expeditions. What makes this lodge special is its location on a bend in the Madi River that offers both calm waters for beginners and challenging rapids for experts. The lodge is particularly famous for its jungle trekking programs that combine river adventures with wildlife spotting in the surrounding forests.', 90.00, 4.5, 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/495791034.jpg?k=795c436219087ab17b14a593c7d80a4f77ec7fb52d3fd740d04c90f0675660da&o=', 12, '["Standard", "Adventure Suite"]'::jsonb),

('Kaskikot Heritage Home', 'Pokhara', 'Founded in 2014, Kaskikot Heritage Home is famous for being located in one of the oldest Magar villages in Nepal, with a history dating back over 500 years. This heritage home is renowned for preserving traditional Magar architecture and cultural practices that are rapidly disappearing. What makes this home special is that it was built using traditional Magar construction techniques that have been passed down through generations. The home is particularly famous for its cultural immersion programs where guests can learn traditional Magar crafts, music, and cooking from village elders.', 40.00, 4.0, 'https://imgs.search.brave.com/9QxhJ2vrgiRTzqSRDK1F2fSpsCbIkfQiwRTcxPjj4jQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMtYXBpLmthdGht/YW5kdXBvc3QuY29t/L3RodW1iLnBocD9z/cmM9aHR0cHM6Ly9h/c3NldHMtY2RuLmth/dGhtYW5kdXBvc3Qu/Y29tL3VwbG9hZHMv/c291cmNlL25ld3Mv/MjAyNi90aGlyZC1w/YXJ0eS9IaW1hbGF5/YW5IaWRlYXdheVJl/c29ydDNjb3B5LTE3/NzA3NzIyODcuanBn/Jnc9OTAwJmhlaWdo/dD02MDE', 8, '["Standard", "Heritage Room"]'::jsonb),

('Lamachaur Mountain View', 'Pokhara', 'Established in 2017, Lamachaur Mountain View is famous for being the highest-altitude hotel in Pokhara, located at 1,800 meters above sea level. This mountain hotel is renowned for offering the most spectacular panoramic views of the entire Annapurna mountain range. What makes this hotel special is its glass-floor observation deck that allows guests to see directly down into the valley below. The hotel is particularly famous for its astronomy program where guests can use professional telescopes to observe the Himalayan night sky and for its sunrise helicopter tours that offer aerial views of the mountains.', 100.00, 4.6, 'https://imgs.search.brave.com/IkgTXzvQ2id32Qz1dLt4RlDnJUO941EkxboAm5KXJmI/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly8yY3Vw/c29mdHJhdmVsLmNv/bS93cC1jb250ZW50/L3VwbG9hZHMvMjAy/NS8wMy9EU0MwMTEy/NC0xMDI0eDY4My5q/cGc', 6, '["Standard", "Mountain View"]'::jsonb),

('Pumdikot Hill Resort', 'Pokhara', 'Founded in 2019, Pumdikot Hill Resort is famous for being built around the newly constructed Pumdikot Shiva Statue, one of the tallest Shiva statues in Nepal. This hilltop resort is renowned for its 360-degree views of Pokhara Valley, Phewa Lake, and the entire Himalayan range. What makes this resort special is its traditional Hindu architecture that incorporates elements from various temples across Nepal. The resort is particularly famous for its spiritual programs that include daily yoga sessions at sunrise and evening meditation with views of the illuminated Shiva statue.', 85.00, 4.4, 'https://imgs.search.brave.com/ogc83T63BTo1iD3MYfYWOy7-7PNNGKHRc-zr1NxwOJQ/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9keW5h/bWljLW1lZGlhLWNk/bi50cmlwYWR2aXNv/ci5jb20vbWVkaWEv/cGFydG5lci9ib29r/aW5nY29tL3Bob3Rv/LW8vMmQvOGUvZmUv/MzIvcHVtZGlrb3Qt/bW91bnRhaW4tbG9k/LmpwZz93PTcwMCZo/PS0xJnM9MQ', 20, '["Standard", "Deluxe", "Hill View"]'::jsonb),

('Tatopani Hill Station', 'Pokhara', 'Established in 2013, Tatopani Hill Station is famous for being located near natural hot springs that have been used for healing for over 2,000 years. This mountain station is renowned for its traditional Nepali hot stone therapy treatments that use stones heated in the natural springs. What makes this station special is its location in a rhododendron forest that bursts into color during spring. The station is particularly famous for its traditional healing programs that combine hot spring therapy with Ayurvedic treatments and for its wildlife viewing opportunities, as the area is home to various Himalayan wildlife species.', 75.00, 4.2, 'https://imgs.search.brave.com/o57U9jzXR1Kp9J1_6CzD4vyNhG3MkXb0Sv3vvR8sE5k/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9oaW1h/bGF5YWd1aWRlbmVw/YWwuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDI1LzA4L0dv/cmthaLS1oaWxsLVN0/YXRpb24taW4tTmVw/YWwuanBn', 15, '["Standard", "Forest View"]'::jsonb),

('Ghorepani Mountain Lodge', 'Pokhara', 'Established in 2011, Ghorepani Mountain Lodge is famous for being located at the starting point of the famous Ghorepani Poon Hill trek, one of Nepal''s most popular short treks. This mountain lodge is renowned for its role in supporting local mountain communities through sustainable tourism practices. What makes this lodge special is its traditional Gurung construction that has been adapted for high-altitude conditions. The lodge is particularly famous for its pre-trek briefing sessions where experienced Sherpa guides share their knowledge of the mountains and for its traditional Gurung cultural performances that showcase mountain hospitality.', 95.00, 4.7, 'https://imgs.search.brave.com/gfRypvdFHyj4E0zMGJFtqEH93FAb0-mCZRogOUrQzNE/rs:fit:500:0:1:0/g:ce/aHR0cDovL2Z1bGx0/aW1lZXhwbG9yZXIu/Y29tL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIxLzEyL0dob3Jl/cGFuaS1OZXBhbC1W/aWxsYWdlLVRyZWst/UG9vbi1IaWxsLTgt/MS5qcGc', 8, '["Standard", "Mountain Suite"]'::jsonb),

('Tirkhe Dhunga View', 'Pokhara', 'Founded in 2016, Tirkhe Dhunga View is famous for being located near the sacred Tirkhe Dhunga rock formation, which is an important pilgrimage site for both Hindus and Buddhists. This hilltop retreat is renowned for its spiritual ambiance and its role as a meditation spot for monks and spiritual seekers. What makes this retreat special is its traditional prayer flag gardens that create a colorful and peaceful atmosphere. The retreat is particularly famous for its guided meditation sessions led by local Buddhist monks and for its traditional butter tea ceremonies that have been practiced for centuries.', 60.00, 4.1, 'https://imgs.search.brave.com/-HHdOWCAQDX8uS3cN6SZ9vUKAdjeXQMbGqTDqEc-ZVg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Ymhha3RhcHVyLmNv/bS93cC1jb250ZW50/L3VwbG9hZHMvMjAy/My8wNS9jeWNsZV9D/b25uZWN0X2JrdC5q/cGc', 12, '["Standard", "Valley View"]'::jsonb),

-- Chitwan & Terai Region Hotels (41-60) - ENHANCED DESCRIPTIONS
('Chitwan Jungle Lodge', 'Chitwan', 'Established in 2008, Chitwan Jungle Lodge is famous for being the first eco-friendly lodge to be built on the edge of Chitwan National Park, a UNESCO World Heritage Site. This jungle lodge is renowned for its partnership with local conservation programs that protect endangered species like the one-horned rhinoceros and Bengal tiger. What makes this lodge special is its traditional Tharu architecture that incorporates sustainable building materials and techniques. The lodge is particularly famous for its expert naturalist guides who lead wildlife safaris and for its traditional Tharu cultural performances that showcase the indigenous culture of the Terai region.', 95.00, 4.4, 'https://imgs.search.brave.com/UxATspyWgRer0I1La_o4xrHARWaI1NqRxH5tboY0TVI/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9ob3Rl/bGFzc29jaWF0aW9u/bmVwYWwub3JnLm5w/L3N0b3JhZ2UvaG90/ZWxzL0F1Z3VzdDIw/MjMvdFFEMzBsTms1/a1ZEdDZ1aVRQaXYu/anBn', 12, '["Standard", "Safari Suite"]'::jsonb),

('Barahi Jungle Lodge', 'Chitwan', 'Founded in 2015, Barahi Jungle Lodge is famous for being Nepal''s first luxury jungle resort that combines five-star amenities with authentic wilderness experiences. This luxury resort is renowned for its exclusive location inside a buffer zone of Chitwan National Park, offering direct access to wildlife habitats. What makes this resort extraordinary is its infinity pool that overlooks the jungle canopy and its glass-walled restaurant that allows wildlife viewing while dining. The resort is particularly famous for its professional jeep safaris led by expert wildlife photographers and for its traditional elephant bathing experiences that have been practiced for centuries.', 120.00, 4.6, 'https://imgs.search.brave.com/BRpZWH7yM5btCC5IgPw7vWFiKBpnyLOtfD_k3UQ0Tyc/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/d2lsZGZyb250aWVy/c3RyYXZlbC5jb20v/dXBsb2FkL21pcmJv/ci9kaHJ1di13aWxk/ZnJvbnRpZXJzdHJh/dmVsLWNvbS8yZTM1/ZTk5OF9DaGl0d2Fu/TmVwYWwyMS5qcGc', 25, '["Standard", "Deluxe", "Jungle Suite"]'::jsonb),

('Meghauli Riverside Resort', 'Chitwan', 'Established in 2010, Meghauli Riverside Resort is famous for being located on the banks of the Rapti River, one of the best spots for wildlife viewing in Chitwan. This riverside resort is renowned for its traditional boat tours that take guests deep into the heart of the national park. What makes this resort special is its partnership with local elephant conservation centers that offer guests the opportunity to participate in elephant care programs. The resort is particularly famous for its riverside barbecues where guests can dine while watching wildlife come to drink at the river and for its bird-watching programs that have spotted over 500 species.', 85.00, 4.3, 'https://imgs.search.brave.com/_4bh-JRPBcMgbdauTdy309G-fkJNmT_WBvPAXfRDTyo/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/YXlib3V0aXF1ZWhv/dGVsLmNvbS9waG90/b3MvMTA2OTc0L21l/Z2hhdWxpLXNlcmFp/LWNoaXR3YW4tbmF0/aW9uYWwtcGFyay1h/LXRhai1zYWZhcmkt/bG9kZ2UtbWVnaGF1/bGktMDAyLTU3Mzky/LTIyMjB4MTQwMC5q/cGc', 18, '["Standard", "Deluxe", "River View"]'::jsonb),

('Kasara Resort', 'Chitwan', 'Founded in 2013, Kasara Resort is famous for being the first modern luxury resort in Chitwan to combine contemporary design with traditional Tharu cultural elements. This resort is renowned for its stunning swimming pool that appears to merge with the surrounding jungle landscape. What makes this resort special is its location on the Kasara River, which is known for being one of the best places to spot freshwater dolphins. The resort is particularly famous for its world-class spa that offers treatments using traditional Tharu herbal remedies and for its gourmet restaurant that serves fusion cuisine combining local Tharu flavors with international cooking techniques.', 75.00, 4.5, 'https://imgs.search.brave.com/8rwK-pDw2wGvfVYQtFLHKALRxdJdY5-cNlz3w_tL-Fs/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Z2V0YXdheW5lcGFs/LmNvbS9pbWFnZXMv/aG90ZWwva2FzYXJh/LXJlc29ydDIuanBn', 20, '["Standard", "Deluxe", "Pool View"]'::jsonb),

('Bharatpur Eco Village', 'Chitwan', 'Established in 2012, Bharatpur Eco Village is famous for being the first authentic Tharu village experience that allows guests to live like locals in the Terai region. This eco-village is renowned for preserving traditional Tharu way of life, including their unique architecture, farming practices, and cultural traditions. What makes this village special is that it is run entirely by the local Tharu community, with profits supporting community development projects. The village is particularly famous for its traditional Tharu dance performances that tell stories of the community''s history and for its organic farming experiences where guests can learn about traditional agricultural practices.', 55.00, 4.1, 'https://imgs.search.brave.com/jd9XxRTZivLwIC42oGoa5vC9Wvg65jKMVGNMmY6mWzo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9hMC5t/dXNjYWNoZS5jb20v/aW0vcGljdHVyZXMv/aG9zdGluZy9Ib3N0/aW5nLTE1ODY3MjU5/MDY3MDY5OTA3NTIv/b3JpZ2luYWwvZjYx/MjliMTctZjg2OS00/YzA3LThiY2UtZDZi/YTI4ZDYxYWE0Lmpw/ZWc', 15, '["Standard", "Village Room"]'::jsonb),

('Jagatpur Forest Retreat', 'Chitwan', 'Founded in 2014, Jagatpur Forest Retreat is famous for being located in a pristine forest area that serves as a corridor for wildlife movement between different parts of Chitwan National Park. This peaceful retreat is renowned for its meditation gardens that were designed according to ancient Buddhist principles. What makes this retreat special is its commitment to sustainable practices, including rainwater harvesting and solar energy. The retreat is particularly famous for its yoga and meditation programs led by local spiritual teachers and for its traditional Nepali cooking classes that use organic ingredients from its own garden.', 65.00, 4.2, 'https://imgs.search.brave.com/knmebBVMVXQ1mysc7EWqufD82q_IJ7KVFy8RCLF1jz0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MjYvYzAvNTkvZjAv/amFnYXRwdXItbG9k/Z2UuanBn', 10, '["Standard", "Deluxe", "Forest View"]'::jsonb),

('Gadhiya Conservation Lodge', 'Chitwan', 'Established in 2016, Gadhiya Conservation Lodge is famous for being the first lodge in Nepal dedicated entirely to wildlife conservation and research. This conservation-focused lodge is renowned for its partnership with international wildlife organizations that conduct important research on endangered species. What makes this lodge extraordinary is that it has its own research center where guests can participate in wildlife monitoring and data collection. The lodge is particularly famous for its educational programs that teach guests about conservation efforts and for its guided night safaris that offer opportunities to spot nocturnal wildlife like leopards and owls.', 90.00, 4.7, 'https://imgs.search.brave.com/R2mmL55YgJrxvjqhueUsPQbx1kIJQ0MIWGKnFIoi6Vc/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9lY29i/bmIuY29tL21l/ZGlhL2NhY2hlL3Jlc29s/dmUvZnVsbF84L21l/ZGlhL3VwbG9hZHMv/NjQ1MjlmNDdiNjE4/Yi5qcGVn', 8, '["Standard", "Conservation Suite"]'::jsonb),

('Ayodhyapuri Wildlife Camp', 'Chitwan', 'Founded in 2017, Ayodhyapuri Wildlife Camp is famous for being the first adventure camp in Nepal to combine jungle trekking with river rafting in the same package. This adventure camp is renowned for its expert guides who are trained in both wildlife tracking and river navigation. What makes this camp special is its location near the confluence of two rivers, creating a unique ecosystem that attracts diverse wildlife. The camp is particularly famous for its multi-day adventure programs that take guests deep into the wilderness and for its traditional camping experiences that include cooking over open fires and sleeping under the stars.', 70.00, 4.4, 'https://imgs.search.brave.com/74v2EYPIjwy8bp7NI6MoOYroy4N_TUvs9Tie7Gwcv7M/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Y29zaGl0YXBwdS5j/b20vd3AtY29udGVu/dC91cGxvYWRzL2tv/c2hpLXRhcHB1LXdp/bGRsaWZlLWNhbXAt/bmVwYWwtcHJlbWlz/cXMtcGhvdG8tMS03/Njh4NTEyLmpwZw', 14, '["Standard", "Adventure Tent"]'::jsonb),

('Madi River Eco Resort', 'Chitwan', 'Established in 2015, Madi River Eco Resort is famous for being the first sustainable resort in Nepal to be powered entirely by renewable energy sources. This eco-resort is renowned for its innovative waste management system that recycles 100% of its waste. What makes this resort special is its location on the Madi River, which is famous for its clean water and diverse fish population. The resort is particularly famous for its traditional fishing programs where guests can learn ancient fishing techniques from local fishermen and for its canoeing tours that take guests through pristine wetland habitats.', 80.00, 4.3, 'https://imgs.search.brave.com/gw3Prry8xzxCCFqyWyjlCMDXdILZ5Xuo2GwQq_-LzpQ/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9hay1k/LnRyaXBjZG4uY29t/L2ltYWdlcy8wMjI1/eDEyMDAwZHdpYmgy/cUM0RjdfV180MDBf/NDAwX1I1LndlYnA_/ZGVmYXVsdD0x', 16, '["Standard", "Eco Suite"]'::jsonb),

('Kumroj Village Homestay', 'Chitwan', 'Founded in 2018, Kumroj Village Homestay is famous for being the first community-based homestay program in Chitwan that directly supports local village development. This authentic homestay is renowned for offering guests the opportunity to live with traditional Tharu families and participate in their daily activities. What makes this homestay special is that all profits go directly to community projects like education and healthcare. The homestay is particularly famous for its traditional cooking classes where guests learn to prepare authentic Tharu cuisine and for its village walks that introduce guests to the local way of life.', 35.00, 4.0, 'https://imgs.search.brave.com/psxALi3mGok7IfacRuxz-nNM5tagndpK_L9RVhSqXcc/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9ocmVj/YWNvdW50eS5jb20v/Y29udGVudC91cGxv/YWRzLzIwMjMvMDIv/SU1HXzAyNjctMS0x/MDI0eDc2OC5qcGc', 6, '["Standard", "Family Room"]'::jsonb),

('Baghmara Community Lodge', 'Chitwan', 'Established in 2011, Baghmara Community Lodge is famous for being the first community-owned and operated lodge in Chitwan, with all profits supporting local conservation efforts. This community lodge is renowned for its role in protecting the Baghmara forest buffer zone, which is an important wildlife corridor. What makes this lodge special is that it is managed by a committee of local villagers who make all decisions collectively. The lodge is particularly famous for its community-based anti-poaching programs and for its traditional Tharu cultural shows that have helped preserve indigenous performing arts.', 60.00, 4.2, 'https://imgs.search.brave.com/LOtyuVU6fA8hHYjVs9vDFZ7pgxQEsvOZdWs7yp1dU-I/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWdz/ZXJ2aWNlLmJlZHJv/b212aWxsYXMuY29t/LzY0MHg0MTcvc2Fw/YW5hLXZpbGxhZ2Ut/bG9kZ2UtbnAtc2F1/cmFoYS1iYy0zMzky/MzgtMC5qcGc', 12, '["Standard", "Community Room"]'::jsonb),

('Gaidakot Jungle Resort', 'Chitwan', 'Founded in 2019, Gaidakot Jungle Resort is famous for having Nepal''s most spectacular infinity pool that appears to float above the jungle canopy. This adventure resort is renowned for its unique location on a cliff edge that offers panoramic views of the surrounding jungle and distant mountains. What makes this resort extraordinary is its glass-bottomed skywalk that allows guests to walk safely above the jungle floor and observe wildlife from above. The resort is particularly famous for its helicopter tours that offer aerial views of the national park and for its gourmet restaurant that serves traditional jungle cuisine with a modern twist.', 100.00, 4.6, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/ad/05/4e/infinity-pool-view-overlooking.jpg?w=1600&h=-1&s=1', 10, '["Standard", "Adventure Suite"]'::jsonb),

('Rapti River Bank Hotel', 'Chitwan', 'Established in 2013, Rapti River Bank Hotel is famous for being located at one of the best crocodile-watching spots along the Rapti River. This riverside hotel is renowned for its traditional boat tours that take guests close to crocodile basking areas and bird nesting sites. What makes this hotel special is its partnership with local conservationists who conduct regular wildlife monitoring from the hotel premises. The hotel is particularly famous for its riverside restaurant that serves fresh fish caught daily from the river and for its evening campfire programs where local naturalists share stories about the jungle.', 68.00, 4.0, 'https://imgs.search.brave.com/fSn-XxFR0uOy0U4hU1Rm_4pf1mVc3BWMqIP2iBEKT00/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MDMvZmUvZWQvY2Uv/cml2ZXItYmFuay1p/bm4uanBn', 18, '["Standard", "Deluxe", "Boat View"]'::jsonb),

-- Lumbini & Religious Sites (61-80) - ENHANCED DESCRIPTIONS
('Lumbini Buddha Garden Hotel', 'Lumbini', 'Founded in 2009, Lumbini Buddha Garden Hotel is famous for being the first hotel in Lumbini to be built within walking distance of the sacred Maya Devi Garden, the birthplace of Lord Buddha. This spiritual hotel is renowned for its traditional monastic architecture that reflects the simplicity and serenity of Buddhist teachings. What makes this hotel special is its meditation gardens that contain plants and flowers mentioned in ancient Buddhist texts. The hotel is particularly famous for its daily meditation sessions led by resident monks and for its vegetarian restaurant that serves meals prepared according to Buddhist dietary principles.', 55.00, 4.1, 'https://imgs.search.brave.com/tpEjePi6kVJb0JObxyLnsXUlA9Kaib3K6GkTLOMpTwk/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pbWcu/ZWFzZW15dHJpcC5j/b20vRU1USE9URUwt/MTE4MzM2Ni84L2cv/cy84MzIxMjJfMTQu/anBn', 14, '["Garden View", "Deluxe"]'::jsonb),

('Maya Devi Temple Lodge', 'Lumbini', 'Established in 2012, Maya Devi Temple Lodge is famous for being the closest accommodation to the sacred Maya Devi Temple, the exact birthplace of Lord Buddha. This sacred hotel is renowned for its role in hosting Buddhist pilgrims from around the world who come to pay homage at this holy site. What makes this lodge special is that every room offers views of the temple complex and its beautiful gardens. The lodge is particularly famous for its participation in daily prayer ceremonies at the temple and for its traditional Buddhist library that contains rare texts and scriptures.', 75.00, 4.4, 'https://imgs.search.brave.com/01uckLRPLl52jUmOwkeNc_TqEif3miZLdROd9pdAg2I/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS5lYXNlbXl0cmlw/LmNvbS9tZWRpYS9I/b3RlbC8vSG90ZWwv/SG90ZWxjbGxUMWou/cG5n', 20, '["Standard", "Deluxe", "Temple View"]'::jsonb),

('Ramagrama Monastery View', 'Lumbini', 'Founded in 2014, Ramagrama Monastery View is famous for being located near the ancient Ramagrama stupa, one of the eight original stupas that contained relics of Lord Buddha. This spiritual retreat is renowned for its partnership with local monasteries that offer guests the opportunity to participate in ancient Buddhist rituals and teachings. What makes this retreat special is its traditional meditation halls that were designed by Buddhist masters from different countries. The retreat is particularly famous for its Buddhist philosophy classes taught by visiting monks and for its peaceful atmosphere that attracts spiritual seekers from around the world.', 45.00, 4.0, 'https://imgs.search.brave.com/eXlKeO1oE8OrARgt33V5HqDoTHVFUh7c3b0_ZkZtr7k/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jZG4u/ZXxlYmFzZS5pby8x/NzNmZTk1My04YTYz/LTRhOGEtOGNhMy0x/YmFjYjU2ZDc4YTUv/OTAyODkxNzYtYzFi/Mi00OTRmLWFhMTYt/YTAxMDRlOTMzODJh/LXJhbWFncmFtYS1n/YWxsZXJ5LTAzLmpw/Zz93PTEwMDAmaD01/MDAmZml0PWNyb3Am/cT03NQ', 10, '["Standard", "Deluxe", "Monastery View"]'::jsonb),

('Shivaraj Garden Hotel', 'Lumbini', 'Founded in 2015, Shivaraj Garden Hotel is famous for being built around traditional lotus ponds that symbolize purity and enlightenment in Buddhist philosophy. This beautiful garden hotel is renowned for its stunning Buddhist architecture that incorporates elements from temples across Asia. What makes this hotel extraordinary is its collection of rare Buddhist artifacts that have been donated by monasteries from different countries. The hotel is particularly famous for its traditional tea ceremonies that follow ancient Buddhist rituals and for its meditation pavilions that offer peaceful spaces for spiritual practice.', 95.00, 4.7, 'https://imgs.search.brave.com/1hssY7eNSA2OWtc7esvDy3az_Eyr8nkrG-WRvXhkVYE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jb250/ZW50LmpkbWFnaWNi/b3guY29tL2NvbXAv/c2F0YXJhL2I4Lzk5/OTlwMjE2Mi4yMTYy/LjE4MTAxNDExMjg0/My5uM2I4L2NhdGFs/b2d1ZS9ob3RlbC1z/aGl2YXItZ2FyZGVu/LWxvbmFuZC1zYXRh/cmEtcmVzdGF1cmFu/dHMtYWZkeGtncThl/cS5qcGc_dz0zODQw/JnE9NzU', 20, '["Standard", "Deluxe", "Garden Suite"]'::jsonb),

-- Annapurna & Mountain Region (81-100) - ENHANCED DESCRIPTIONS
('Annapurna Base Camp Lodge', 'Annapurna', 'Established in 2010, Annapurna Base Camp Lodge is famous for being the highest-altitude lodge in Nepal, located at 4,130 meters at the base of the world''s tenth-highest mountain. This mountain lodge is renowned for its role as the final staging point for climbers attempting to summit Annapurna I. What makes this lodge extraordinary is its construction using traditional Sherpa building techniques adapted for extreme altitude conditions. The lodge is particularly famous for its role in numerous high-altitude rescue operations and for its experienced Sherpa guides who have summited major peaks multiple times.', 140.00, 4.8, 'https://imgs.search.brave.com/sztcZ4U1TRqJ3pzE8ZLCSYaFUOeb5eUPISl9pkCcGUQ/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9ib2xk/YWR2ZW50dXJlc25l/cGFsLmNvbS93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyMy8wNy9s/b2RnZS10cmF2ZWxl/ci1vbi1tb3VudGFp/bi53ZWJw', 6, '["Standard", "Mountain View"]'::jsonb),

('Ghandruk Village Lodge', 'Annapurna', 'Founded in 2008, Ghandruk Village Lodge is famous for being located in one of the most picturesque Gurung villages in the Annapurna region, with stunning views of the Annapurna South face. This traditional village lodge is renowned for preserving authentic Gurung architecture and cultural practices. What makes this lodge special is that it is owned and operated by a local Gurung family who have lived in the village for generations. The lodge is particularly famous for its traditional Gurung cultural shows that feature ancient warrior dances and for its role in supporting community development projects in the village.', 80.00, 4.5, 'https://imgs.search.brave.com/epYmWVgEwVoB6T83rX2nVxOFC0mMv1b97ee5rCMbwc4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/YXVkbGV5dHJhdmVs/LmNvbS83NTIvNTM3/LzU1LzI3NTQ0Ni1o/aW1hbGF5YS1sb2Rn/ZS1naGFuZHJ1ay5q/cGc', 12, '["Standard", "Village Room"]'::jsonb),

('Chhomrong Hill View', 'Annapurna', 'Founded in 2016, Chhomrong Hill View is famous for being located in the traditional Gurung village of Chhomrong, the gateway to the Annapurna Base Camp trek. This hilltop hotel is renowned for its spectacular views of both the Annapurna South face and the Modi River valley below. What makes this hotel special is its traditional Gurung architecture that features intricate woodcarvings and stone work. The hotel is particularly famous for its role as a major acclimatization stop for trekkers and for its traditional Gurung cultural programs that showcase mountain hospitality and ancient traditions.', 95.00, 4.6, 'https://imgs.search.brave.com/xHeMmdYXGoOGu2eWs7r_we0erSvXWtGLCy24r2m5owU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90aHVt/bnMuZHJlYW1zdGlt/ZS5jb20vYi92aWV3/LWNoaG9tcm9uZy10/b3duLWxpdHRsZS12/aWxsYWdlLW1pZGRs/ZS1hbm5hcHVybmEt/YmFzZS1jYW1wLXRy/ZWstY2hob21yb25n/LW5lcGFsLXZpZXcv/Y2hob21yb25nLXRv/d24tbGl0dGxlLTI3/Mjk2MzcwMi5qcGc', 15, '["Standard", "Deluxe", "Mountain View"]'::jsonb),

('Dhampus Mountain Retreat', 'Annapurna', 'Established in 2014, Dhampus Mountain Retreat is famous for being located in the traditional Magar village of Dhampus, known for its stunning sunrise views over the entire Annapurna range. This peaceful mountain retreat is renowned for its role in promoting sustainable tourism practices that benefit the local community. What makes this retreat special is its traditional Magar construction techniques that have been adapted for modern comfort. The retreat is particularly famous for its sunrise yoga sessions with mountain views and for its cultural programs that introduce guests to traditional Magar music and dance.', 110.00, 4.4, 'https://imgs.search.brave.com/qbCu8lin_DXT1EQEe6russzZgjIger3VHnjPZQzGH0Y/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/YXV0aGVudGljaW5k/YWF0b3Vycy5jb20v/YXBwL3VwbG9hZHMv/MjAyMi8wNS9MYS1C/ZWUtTG9kZ2UtTGFu/ZHJ1ay1OZXBhbC0x/NDAweDU1MC0xLTE0/MDB4NTUwLWMtZGVm/YXVsdC5qcGc', 18, '["Standard", "Deluxe", "Sunrise View"]'::jsonb),

('Landruk Riverside Lodge', 'Annapurna', 'Founded in 2015, Landruk Riverside Lodge is famous for being located in the picturesque village of Landruk, situated along the banks of the Modi River with stunning views of the Annapurna mountains. This riverside lodge is renowned for its traditional Gurung architecture that features beautiful stone walls and wooden balconies. What makes this lodge special is its location on the famous Annapurna Circuit trekking route. The lodge is particularly famous for its riverside dining experiences where guests can enjoy traditional Gurung cuisine while watching the river flow and for its cultural programs that showcase traditional mountain hospitality.', 75.00, 4.3, 'https://imgs.search.brave.com/qbCu8lin_DXT1EQEe6russzZgjIger3VHnjPZQzGH0Y/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/YXV0aGVudGljaW5k/YWF0b3Vycy5jb20v/YXBwL3VwbG9hZHMv/MjAyMi8wNS9MYS1C/ZWUtTG9kZ2UtTGFu/ZHJ1ay1OZXBhbC0x/NDAweDU1MC0xLTE0/MDB4NTUwLWMtZGVm/YXVsdC5qcGc', 20, '["Standard", "Deluxe", "River View"]'::jsonb),

('Australian Camp View', 'Annapurna', 'Founded in 2014, Australian Camp View is famous for being located at the historic Australian Camp site, which was established by Australian trekkers in the 1970s and became one of the first tourist destinations in the Annapurna region. This historic camp site hotel is renowned for its role in the development of trekking tourism in Nepal. What makes this hotel special is its traditional tea gardens that were planted by the original Australian trekkers and still produce high-quality tea. The hotel is particularly famous for its panoramic views of the Annapurna South Face and for its collection of historical photographs that document the early days of trekking in Nepal.', 85.00, 4.2, 'https://imgs.search.brave.com/xb38N3t3-8PBC678dDHR8F4QA6hsAWdgKV2iuf-D-So/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93aWxk/ZWJuZXNzZXhjdXJz/aW9uLmNvbS9fbmV4/dC9pbWFnZT91cmw9/aHR0cHM6Ly9tZWRp/YS5hcHAud2lsZGVy/bmVzc2V4Y3Vyc2lv/bi5jb20vdXBsb2Fk/cy9mdWxsYmFubmVy/L3RodWxvLWtoYXJr/YS53ZWJwJnc9Mzg0/MCZxPTc1JmRwbD1k/cGxfOGZwdkd2TDNV/SDRyM3c2b0ZMTEdX/eDhGdTZuYw', 25, '["Standard", "Deluxe", "Camp View"]'::jsonb),

('Pothana Mountain Resort', 'Annapurna', 'Established in 2016, Pothana Mountain Resort is famous for being located at one of the highest accessible points in the Annapurna region, offering spectacular views of both the Annapurna and Dhaulagiri mountain ranges. This high-altitude resort is renowned for its role as an acclimatization stop for trekkers attempting high-altitude climbs. What makes this resort special is its traditional stone construction that has been tested against extreme mountain weather conditions. The resort is particularly famous for its altitude sickness prevention programs and for its experienced mountain guides who have led numerous successful expeditions.', 120.00, 4.7, 'https://imgs.search.brave.com/pJxDIKNiY2xKHwRPGCS2-JE2ECVa6EiqjGRbz101v3c/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jb250/ZW50LmpkbWFnaWNi/b3guY29tL3YyL2Nv/bXAvbXVubmFyL3k4/Lzk5OTlwNDg2NS40/ODY1LjEwMDQzMDE1/NDAzNS5lN3k4L2Nh/dGFsb2d1ZS9kZXNo/YWRhbi1tb3VudGFp/bi1yZXNvcnQtcG90/aGFtZWR1LW11bm5h/ci0zLXN0YXItcmVz/b3J0cy0yYXQ4ZjVi/OHp2LmpwZz93PTM4/NDAmcT03NQ', 8, '["Standard", "Deluxe", "Mountain Suite"]'::jsonb),

('Jhinu Danda Sunrise', 'Annapurna', 'Founded in 2013, Jhinu Danda Sunrise is famous for being located at the site of natural hot springs that have been used by trekkers for decades to soothe sore muscles after long treks. This sunrise viewpoint hotel is renowned for offering some of the most spectacular morning views in the entire Annapurna region. What makes this hotel special is its traditional hot stone bath facilities that use stones heated in natural spring water. The hotel is particularly famous for its sunrise yoga sessions that combine yoga practice with hot spring relaxation and for its role as a popular meeting point for trekkers from around the world.', 80.00, 4.4, 'https://imgs.search.brave.com/tl9_0gyWj7n9D2BChbf_ZAOtLqX-e0EpZGR3ZFaTf6w/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9hd2Vz/b21laG9saWRheXNu/ZXBhbC5jb20vd3At/Y29udGVudC91cGxv/YWRzLzIwMjUvMDMv/SmhpbnUtRGFuZGEu/anBn', 20, '["Standard", "Deluxe", "Sunrise Suite"]'::jsonb),

('Ghandruk Eco Village', 'Annapurna', 'Founded in 2017, Ghandruk Eco Village is famous for being the first sustainable mountain village in Nepal that combines traditional Gurung culture with modern environmental practices. This eco-village is renowned for its zero-waste policy and its use of renewable energy sources in a remote mountain setting. What makes this village special is that it was built in partnership with the local Gurung community to preserve their traditional way of life while improving living standards. The village is particularly famous for its traditional craft workshops where guests can learn ancient Gurung weaving and metalworking techniques.', 60.00, 4.1, 'https://imgs.search.brave.com/bVeJLvpXevAaWPZbz13LASq1-QOorNa8dOfpmFtMIJ0/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9hc2lh/bmhlcml0YWdldHJl/a3MuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIzLzAyL2do/YW5kcnVrLXZpbGxh/Z2UuanBn', 14, '["Standard", "Eco Room"]'::jsonb);

-- Verify the data
SELECT COUNT(*) as total_hotels FROM public.hotels;
